###
POST {{URL}}/hotel
Content-Type: application/json

{
  "hotelName": "lastHotelName",
  "hotelAddress": "lastHotelAddress",
  "rooms": [
    {
      "roomNumber": 888,
      "roomPrice": 888.0
    },
    {
      "roomNumber": 999,
      "roomPrice": 999.0
    }
  ]
}

###
GET {{URL}}/hotel

###
GET {{URL}}/hotel/2

###
GET {{URL}}/hotel/2/rooms

###
PUT {{URL}}/hotel/13
Content-Type: application/json

{
  "hotelName": "Hotel name updated4",
  "hotelAddress": "Hotel address updated2"
  }

###
DELETE {{URL}}/hotel/15