###
POST {{URL}}
Content-Type: application/json

{
  "hotelName": "postedHotel",
  "hotelAddress": "postedHotelAddress",
  "rooms": [
    {
      "roomNumber": 123,
      "roomPrice": 100.0
    },
    {
      "roomNumber": 456,
      "roomPrice": 200.0
    }
  ]
}

###
GET {{URL}}

###
GET {{URL}}/2

###
PUT {{URL}}/4
Content-Type: application/json

{
  "dogName": "Rex updated",
  "dogAge": 3,
  "dogBreed": "LABRADOR",
  "dogGender": "MALE"
  }

###
DELETE {{URL}}/3